version: '3.1'
services:
  odoo:
    image: odoo:16.0
    ports:
      - "8000:8069"
    command: ["--log-level=debug"]
    container_name: "odoo-16"
    restart: "unless-stopped"
    volumes:
      - ./conf:/etc/odoo
      - ./addons:/mnt/extra-addons
    
    networks:
      - dockernet

networks:
  dockernet:
    name: dockernet
    external: true